services:
  report-bot:
    image: ghcr.io/liante0904/naver-stock-report:latest
    container_name: naver-stock-report-bot-${APP_ENV:-prod}
    user: "1001:1001"
    restart: always
    env_file: .env
    environment:
      - APP_ENV=${APP_ENV:-prod}
      - TZ=Asia/Seoul
    volumes:
      - ./app.py:/app/app.py
      - ~/sqlite3:/app/db
      - ~/log:/app/log
    networks:
      - public-net

networks:
  public-net:
    external: true
