services:
  report-bot:
    image: ghcr.io/liante0904/naver-stock-report:latest
    container_name: naver-stock-report-bot
    user: "1001:1001"
    restart: always
    env_file: .env
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ~/sqlite3:/app/db
      - ~/log:/app/log
